# Generated by Django 5.2.5 on 2025-09-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_alter_jobs_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
