# Generated by Django 5.2.6 on 2025-10-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20251023_0959'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_application_per_jobseeker_job',
        ),
    ]
