# Generated by Django 5.2.5 on 2025-09-18 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobSeekerProfile', '0001_initial'),
        ('Jobs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('AC', 'Accept'), ('RJ', 'Reject')], default='P', max_length=50, null=True)),
                ('cover_letter_text', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
                ('job_seeker_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobSeekerProfile.jobseekerprofile')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSeekerProfile.resume')),
            ],
        ),
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeekerProfile.jobseekerprofile')),
            ],
        ),
    ]
