# Generated by Django 5.2.6 on 2025-09-05 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobSeekerProfile', '0002_alter_education_id_alter_experience_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('cover_letter_text', models.TextField(blank=True, null=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeekerProfile.jobseekerprofile')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSeekerProfile.resume')),
            ],
        ),
    ]
