<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-13 12:52
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-13 12:52
=======
# Generated by Django 5.2.6 on 2025-10-09 01:58
>>>>>>> 7e3badd25fec1e19969e1a07a042fa140e4e364c
>>>>>>> 1a85d44ec57cf4f66837744eb5e00f6e92626933
>>>>>>> 0899fb49c3db3f31405b7af66b45eb30b85be48c

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('JobSeekerProfile', '0003_alter_resume_profile'),
        ('Jobs', '0009_alter_jobs_location'),
<<<<<<< HEAD

=======
=======
<<<<<<< HEAD
        ('JobSeekerProfile', '0003_alter_resume_profile'),
        ('Jobs', '0009_alter_jobs_location'),
=======
        ('JobSeekerProfile', '0003_remove_skill_proficiency_education_description_and_more'),
        ('Jobs', '0006_alter_jobs_location'),
>>>>>>> 7e3badd25fec1e19969e1a07a042fa140e4e364c
>>>>>>> 1a85d44ec57cf4f66837744eb5e00f6e92626933
>>>>>>> 0899fb49c3db3f31405b7af66b45eb30b85be48c
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_form', models.JSONField(blank=True, default=None, null=True)),
                ('resume_upload', models.ImageField(blank=True, null=True, upload_to='resume-file')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('AC', 'Accept'), ('RJ', 'Reject')], default='P', max_length=50, null=True)),
                ('cover_letter_text', models.TextField(null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Jobs.jobs')),
                ('job_seeker_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobSeekerProfile.jobseekerprofile')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSeekerProfile.resume')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_seeker_profile', 'job'), name='unique_application_per_jobseeker_job'), models.CheckConstraint(condition=models.Q(models.Q(('resume__isnull', False), ('resume_form__isnull', True)), models.Q(('resume__isnull', True), ('resume_form__isnull', False)), _connector='OR'), name='app_resume_xor_form')],
            },
        ),
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='JobSeekerProfile.jobseekerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'job'), name='unique_save_job_per_jobseeker_job')],
            },
        ),
    ]
