# Generated by Django 5.2.5 on 2025-09-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
        ('JobSeekerProfile', '0003_remove_resume_file_type_remove_resume_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSeekerProfile.resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_upload',
            field=models.ImageField(blank=True, null=True, upload_to='resume-file'),
        ),
    ]
