# Generated by Django 5.2.5 on 2025-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
        ('JobSeekerProfile', '0001_initial'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job_seeker_profile', 'job'), name='unique_application_per_jobseeker_job'),
        ),
    ]
