# Generated by Django 5.2.6 on 2025-09-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='edit_at',
            new_name='updated',
        ),
    ]
