# Generated by Django 5.2.6 on 2025-09-05 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Application', '0001_initial'),
        ('JobSeekerProfile', '0002_alter_education_id_alter_experience_id_and_more'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savejob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs'),
        ),
        migrations.AddField(
            model_name='savejob',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeekerProfile.jobseekerprofile'),
        ),
    ]
