# Generated by Django 5.2.6 on 2025-09-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_rename_edit_at_application_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
