# Generated by Django 5.2.5 on 2025-09-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_application_unique_application_per_jobseeker_job'),
        ('JobSeekerProfile', '0001_initial'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savejob',
            constraint=models.UniqueConstraint(fields=('profile', 'job'), name='unique_save_job_per_jobseeker_job'),
        ),
    ]
