# Generated by Django 5.2.5 on 2025-09-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_savejob_unique_save_job_per_jobseeker_job'),
        ('JobSeekerProfile', '0002_alter_skill_profile'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_seeker_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobSeekerProfile.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSeekerProfile.resume'),
        ),
    ]
