# Generated by Django 5.2.5 on 2025-10-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_rename_updated_application_updated_at'),
        ('JobSeekerProfile', '0002_jobseekerprofile_github_jobseekerprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savejob',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='JobSeekerProfile.jobseekerprofile'),
        ),
    ]
