# Generated by Django 5.2.5 on 2025-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_application_created_at_application_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('AC', 'Accept'), ('RJ', 'Reject')], default='P', max_length=50, null=True),
        ),
    ]
