# Generated by Django 5.2.6 on 2025-10-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_rename_updated_at_application_edit_at'),
        ('Application', '0004_alter_savejob_profile'),
    ]

    operations = [
    ]
