# Generated by Django 5.2.6 on 2025-10-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_merge_20251004_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='edit_at',
            new_name='updated_at',
        ),
    ]
