# Generated by Django 5.2.5 on 2025-10-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_merge_20251004_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='edit_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='application',
            name='max_applicants',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of allowed applicants', null=True),
        ),
    ]
