# Generated by Django 5.2.5 on 2025-10-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_rename_edit_at_application_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='max_applicants',
        ),
    ]
