# Generated by Django 5.2.5 on 2025-10-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_remove_application_max_applicants'),
        ('Jobs', '0004_alter_jobs_max_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Jobs.jobs'),
        ),
    ]
