[build]
  builder = "nixpacks"
  buildCommand = "python manage.py collectstatic --noinput"

[deploy]
  startCommand = "gunicorn JobSeeker.wsgi:application"
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"

[envs]
  SECRET_KEY = "${SECRET_KEY}"
  DEBUG = "False"
  EMAIL_HOST_USER = "${EMAIL_HOST_USER}"
  EMAIL_HOST_PASSWORD = "${EMAIL_HOST_PASSWORD}"
  DATABASE_URL = "${DATABASE_URL}"