# Generated by Django 5.2.5 on 2025-10-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True),
        ),
    ]
