# Generated by Django 5.2.5 on 2025-09-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0002_alter_skill_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file_url',
        ),
        migrations.AddField(
            model_name='resume',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resume-file/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='JobSeekerProfile.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('profile',), name='one_default_resume_per_profile'),
        ),
    ]
