# Generated by Django 5.2.5 on 2025-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0003_remove_resume_file_type_remove_resume_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True),
        ),
    ]
