# Generated by Django 5.2.6 on 2025-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_remove_application_unique_application_per_jobseeker_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('H', 'Hired'), ('RJ', 'Rejected'), ('R', 'Review'), ('SL', 'ShortList')], default='P', max_length=50, null=True),
        ),
    ]
