# Generated by Django 5.2.5 on 2025-08-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
