# Generated by Django 5.2.5 on 2025-08-30 01:05

import Accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', Accounts.models.CustomUserManager()),
            ],
        ),
    ]
