# Generated by Django 5.2.5 on 2025-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Jobseeker')], default='jobseeker', max_length=20),
        ),
    ]
