<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-10 06:18
=======
# Generated by Django 5.2.5 on 2025-09-12 06:30
>>>>>>> ede8e9dd866e1f731539a93776b53cc0e3fd5729

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, default='default.png', null=True, upload_to='upload_to_logo')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
