# Generated by Django 5.2.5 on 2025-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerProfile', '0002_employerprofile_industry_employerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='upload_to_logo'),
        ),
    ]
