# Generated by Django 5.2.5 on 2025-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerProfile', '0003_alter_employerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='upload_to_logo'),
        ),
    ]
