# Generated by Django 5.2.5 on 2025-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerProfile', '0004_employerprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='upload_to_logo'),
        ),
    ]
