# Generated by Django 5.2.5 on 2025-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerProfile', '0005_alter_employerprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
